set(SOURCE_FILES
    details/to_big_endian_test.cpp
    memory_output_stream_test.cpp
    serialization_buffer_test.cpp
    serialize_test.cpp
    type_support/bool_test.cpp
    type_support/float_test.cpp
    type_support/integer_test.cpp
)
