set(SOURCE_FILES
    details/to_big_endian_test.cpp
    memory_output_stream_test.cpp
    serialization_buffer_test.cpp
    serialize_test.cpp
    type_support/bool_test.cpp
    type_support/deque_test.cpp
    type_support/float_test.cpp
    type_support/integer_test.cpp
    type_support/list_test.cpp
    type_support/nullptr_test.cpp
    type_support/optional_test.cpp
    type_support/string_test.cpp
    type_support/vector_test.cpp
)
