set(SOURCE_FILES
    details/basic_binary_buffer_test.cpp
    details/buffered_serialization_buffer_impl_test.cpp
    details/count_arguments_macro_test.cpp
    details/non_buffered_serialization_buffer_impl_test.cpp
    details/to_big_endian_test.cpp
    details/total_size_of_test.cpp
    memory_output_stream_test.cpp
    serialization_buffer_test.cpp
    serialize_test.cpp
    type_support/array_test.cpp
    type_support/bool_test.cpp
    type_support/deque_test.cpp
    type_support/float_test.cpp
    type_support/forward_list_test.cpp
    type_support/integer_test.cpp
    type_support/list_test.cpp
    type_support/map_test.cpp
    type_support/nullptr_test.cpp
    type_support/optional_test.cpp
    type_support/pair_test.cpp
    type_support/set_test.cpp
    type_support/string_test.cpp
    type_support/struct_test.cpp
    type_support/timespec_test.cpp
    type_support/tuple_test.cpp
    type_support/unordered_map_test.cpp
    type_support/unordered_set_test.cpp
    type_support/vector_test.cpp
)
