#include "memory_output_stream_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialization_buffer_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialize_test.cpp"             // NOLINT(bugprone-suspicious-include)
#include "type_support/bool_test.cpp"     // NOLINT(bugprone-suspicious-include)
#include "type_support/float_test.cpp"    // NOLINT(bugprone-suspicious-include)
#include "type_support/integer_test.cpp"  // NOLINT(bugprone-suspicious-include)
