set(SOURCE_FILES
    serialize_booleans_test.cpp
    serialize_chrono_time_point_test.cpp
    serialize_ext_test.cpp
    serialize_floating_point_numbers_test.cpp
    serialize_integers_test.cpp
    serialize_maps_test.cpp
    serialize_optional_values_test.cpp
    serialize_strings_test.cpp
    serialize_struct_general_test.cpp
    serialize_struct_test.cpp
    serialize_timespec_test.cpp
    serialize_to_file_test.cpp
    serialize_unordered_map_test.cpp
    serialize_unordered_set_test.cpp
    serialize_vectors_test.cpp
)
