#include "serialize_booleans_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialize_floating_point_numbers_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialize_integers_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialize_optional_values_test.cpp"  // NOLINT(bugprone-suspicious-include)
#include "serialize_strings_test.cpp"  // NOLINT(bugprone-suspicious-include)
